=begin
#SCORM Cloud Rest API

#REST API used for SCORM Cloud integrations.

OpenAPI spec version: 2.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'date'


module RusticiSoftwareCloudV2
  class PublicInvitationSchema
    # The invitationId for this invitation.
    attr_accessor :id

    # Course Id for this Invitation.
    attr_accessor :course_id

    # Determines if learners are allowed to launch the invitation. If false, the invitation is disabled and no new or existing learners are allowed to launch it. 
    attr_accessor :allow_launch

    attr_accessor :invitation_email

    # Determines if new registrations can be created for this public invitation. If false, no new registrations can be created for the invitation, so only learners with existing registrations can access the invitation. 
    attr_accessor :allow_new_registrations

    # The launch URL for the invitation
    attr_accessor :url

    # The create date for the invitation
    attr_accessor :create_date

    attr_accessor :updated

    # Specifies a URL for which to post activity and status data in real time as the course is completed
    attr_accessor :post_back

    # The ISO 8601 TimeStamp (defaults to UTC) after which this invitation will expire and can no longer be launched. An empty value will represent no expiration date. 
    attr_accessor :expiration_date

    # Integer value that represents the maximum number of registrations that can be created for a public invitation. Setting this value to '0' allows an unlimited amount of registrations to be created for the invitation. 
    attr_accessor :registration_cap

    # The count of registrations for this invitation
    attr_accessor :registration_count

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'course_id' => :'courseId',
        :'allow_launch' => :'allowLaunch',
        :'invitation_email' => :'invitationEmail',
        :'allow_new_registrations' => :'allowNewRegistrations',
        :'url' => :'url',
        :'create_date' => :'createDate',
        :'updated' => :'updated',
        :'post_back' => :'postBack',
        :'expiration_date' => :'expirationDate',
        :'registration_cap' => :'registrationCap',
        :'registration_count' => :'registrationCount'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'id' => :'String',
        :'course_id' => :'String',
        :'allow_launch' => :'BOOLEAN',
        :'invitation_email' => :'InvitationEmailSchema',
        :'allow_new_registrations' => :'BOOLEAN',
        :'url' => :'String',
        :'create_date' => :'DateTime',
        :'updated' => :'DateTime',
        :'post_back' => :'PostBackSchema',
        :'expiration_date' => :'DateTime',
        :'registration_cap' => :'Integer',
        :'registration_count' => :'Integer'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.has_key?(:'courseId')
        self.course_id = attributes[:'courseId']
      end

      if attributes.has_key?(:'allowLaunch')
        self.allow_launch = attributes[:'allowLaunch']
      end

      if attributes.has_key?(:'invitationEmail')
        self.invitation_email = attributes[:'invitationEmail']
      end

      if attributes.has_key?(:'allowNewRegistrations')
        self.allow_new_registrations = attributes[:'allowNewRegistrations']
      end

      if attributes.has_key?(:'url')
        self.url = attributes[:'url']
      end

      if attributes.has_key?(:'createDate')
        self.create_date = attributes[:'createDate']
      end

      if attributes.has_key?(:'updated')
        self.updated = attributes[:'updated']
      end

      if attributes.has_key?(:'postBack')
        self.post_back = attributes[:'postBack']
      end

      if attributes.has_key?(:'expirationDate')
        self.expiration_date = attributes[:'expirationDate']
      end

      if attributes.has_key?(:'registrationCap')
        self.registration_cap = attributes[:'registrationCap']
      else
        self.registration_cap = 0
      end

      if attributes.has_key?(:'registrationCount')
        self.registration_count = attributes[:'registrationCount']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end


    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          course_id == o.course_id &&
          allow_launch == o.allow_launch &&
          invitation_email == o.invitation_email &&
          allow_new_registrations == o.allow_new_registrations &&
          url == o.url &&
          create_date == o.create_date &&
          updated == o.updated &&
          post_back == o.post_back &&
          expiration_date == o.expiration_date &&
          registration_cap == o.registration_cap &&
          registration_count == o.registration_count
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [id, course_id, allow_launch, invitation_email, allow_new_registrations, url, create_date, updated, post_back, expiration_date, registration_cap, registration_count].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = RusticiSoftwareCloudV2.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
