=begin
#SCORM Cloud Rest API

#REST API used for SCORM Cloud integrations.

OpenAPI spec version: 2.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'date'

module RusticiSoftwareCloudV2
  class RegistrationSuccess
    
    UNKNOWN = "UNKNOWN".freeze
    PASSED = "PASSED".freeze
    FAILED = "FAILED".freeze

    def build_from_hash(value)
      self.class.constants.each do |sym|
        valid_enum_str = self.class.const_get sym
        return valid_enum_str if value == valid_enum_str
      end
      raise "Encountered unexpected value #{value.inspect} in #{self.class}"
    end
  end

end
